-- Fixed 50 Sample MTG Cards for user1 (user_id = 1)
USE mtg_site;

INSERT INTO inventory (user_id, card_name, quantity) VALUES
(1, 'Lightning Bolt', 1),
(1, 'Counterspell', 1),
(1, 'Black Lotus', 1),
(1, 'Time Walk', 1),
(1, 'Ancestral Recall', 1),
(1, 'Brainstorm', 1),
(1, 'Wrath of God', 1),
(1, 'Swords to Plowshares', 1),
(1, 'Shivan Dragon', 1),
(1, 'Serra Angel', 1),
(1, 'Sol Ring', 1),
(1, 'Dark Ritual', 1),
(1, 'Giant Growth', 1),
(1, 'Llanowar Elves', 1),
(1, 'Birds of Paradise', 1),
(1, 'Mana Leak', 1),
(1, 'Path to Exile', 1),
(1, 'Goblin Guide', 1),
(1, 'Tarmogoyf', 1),
(1, 'Snapcaster Mage', 1),
(1, 'Vendilion Clique', 1),
(1, 'Liliana of the Veil', 1),
(1, 'Jace, the Mind Sculptor', 1),
(1, 'Toxic Deluge', 1),
(1, 'Force of Will', 1),
(1, 'Ponder', 1),
(1, 'Preordain', 1),
(1, 'Demonic Tutor', 1),
(1, 'Diabolic Edict', 1),
(1, 'Thoughtseize', 1),
(1, 'Inquisition of Kozilek', 1),
(1, 'Fatal Push', 1),
(1, 'Chalice of the Void', 1),
(1, 'Umezawa''s Jitte', 1),
(1, 'Batterskull', 1),
(1, 'Stoneforge Mystic', 1),
(1, 'Mother of Runes', 1),
(1, 'Rest in Peace', 1),
(1, 'Leyline of Sanctity', 1),
(1, 'Ensnaring Bridge', 1),
(1, 'Blood Moon', 1),
(1, 'Magus of the Moon', 1),
(1, 'Aether Vial', 1),
(1, 'Mox Opal', 1),
(1, 'Urza''s Tower', 1),
(1, 'Urza''s Mine', 1),
(1, 'Urza''s Power Plant', 1),
(1, 'Karn Liberated', 1),
(1, 'Walking Ballista', 1),
(1, 'Wurmcoil Engine', 1);